[package]
name = "VirtualGamePad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vigem-client = "0.1.4"
time = "0.3.31"
rand = { version = "0.8.5", features = [] }